# Generated by Django 4.2.11 on 2025-02-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vroom", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=255)),
                ("lastname", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=10)),
                ("joined_date", models.DateField()),
            ],
        ),
    ]
