# Generated by Django 4.2.11 on 2025-02-08 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.CharField(max_length=13, primary_key=True, serialize=False),
                ),
                ("firstname", models.CharField(max_length=55)),
                ("lastname", models.CharField(max_length=55)),
                ("phone", models.CharField(max_length=10)),
                ("joined_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=255)),
                ("lastname", models.CharField(max_length=255)),
                ("userlogin", models.EmailField(blank=True, max_length=200)),
                ("userpass", models.CharField(blank=True, max_length=13)),
                ("phone", models.CharField(max_length=10)),
                ("joined_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="UserType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usertype", models.CharField(max_length=5)),
                ("userdetail", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="VideoClip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("published_date", models.DateField(null=True)),
                ("fileclip", models.FileField(blank=True, upload_to="")),
                ("shortdetail", models.CharField(default="", max_length=300)),
                ("demo", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ContactPerson",
            fields=[
                (
                    "author_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="elearning.author",
                    ),
                ),
            ],
            bases=("elearning.author",),
        ),
        migrations.CreateModel(
            name="CourseOwner",
            fields=[
                (
                    "author_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="elearning.author",
                    ),
                ),
            ],
            bases=("elearning.author",),
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="elearning.user",
                    ),
                ),
                ("expire_date", models.DateField(null=True)),
                ("approve", models.BooleanField(blank=True, default=False)),
            ],
            bases=("elearning.user",),
        ),
        migrations.AddField(
            model_name="user",
            name="usertype",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="elearning.usertype",
            ),
        ),
        migrations.CreateModel(
            name="OnlineCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(default="", max_length=250)),
                ("cover", models.ImageField(blank=True, upload_to="")),
                ("briefdetail", models.CharField(blank=True, max_length=500)),
                ("saleprice", models.IntegerField(default=299)),
                ("approve", models.BooleanField(default=False)),
                ("published_date", models.DateField(null=True)),
                (
                    "videoclip",
                    models.ManyToManyField(blank=True, to="elearning.videoclip"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="elearning.member",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaySubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pay_date", models.DateTimeField()),
                ("paidprice", models.IntegerField(blank=True, default=599)),
                ("checkpaid", models.BooleanField(default=False)),
                (
                    "member",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="elearning.member",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pay_date", models.DateTimeField()),
                ("paidprice", models.IntegerField(blank=True, default=299)),
                ("checkpaid", models.BooleanField(default=False)),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="elearning.onlinecourse",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="elearning.member",
                    ),
                ),
            ],
        ),
    ]
